# Generated by Django 4.1.5 on 2023-05-03 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_image', models.ImageField(default='something.img', upload_to='auction/')),
                ('prod_name', models.CharField(default='', max_length=122)),
                ('prod_desc', models.CharField(default='', max_length=122)),
                ('seller', models.CharField(default='', max_length=122)),
                ('artist', models.CharField(default='', max_length=122)),
                ('prod_start_price', models.IntegerField(default=0)),
                ('prod_price', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 5, 3, 15, 18, 44, 16783))),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('duration_mins', models.PositiveIntegerField(default=5)),
                ('end_time', models.DateTimeField(default=datetime.datetime(2023, 5, 3, 15, 18, 44, 16783))),
                ('winner_email', models.CharField(default='default@gmail.com', max_length=122)),
                ('second_email', models.CharField(default='default@gmail.com', max_length=122)),
                ('graph', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(default='', max_length=122)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(default='', max_length=122, unique='true')),
                ('password', models.CharField(default='', max_length=122)),
            ],
        ),
    ]
