# Generated by Django 4.1.7 on 2023-04-09 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(default='', max_length=122)),
                ('prod_image', models.ImageField(default='something.img', upload_to='images/')),
                ('prod_name', models.CharField(default='', max_length=122)),
                ('prod_desc', models.CharField(default='', max_length=122)),
                ('seller', models.CharField(default='', max_length=122)),
                ('artist', models.CharField(default='', max_length=122)),
                ('prod_start_price', models.IntegerField(default=0)),
                ('prod_price', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 13, 11, 19, 734102))),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('duration_mins', models.PositiveIntegerField(default=5)),
                ('end_time', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 13, 11, 19, 735110))),
                ('winner_email', models.CharField(default='', max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(default='', max_length=122)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(default='', max_length=122, unique='true')),
                ('password', models.CharField(default='', max_length=122)),
            ],
        ),
    ]
