# Generated by Django 4.1.5 on 2023-05-02 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_auctionproduct_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 13, 59, 37, 200222)),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='graph',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 13, 59, 37, 200222)),
        ),
    ]
