# Generated by Django 4.1.5 on 2023-05-03 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_alter_auctionproduct_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='second_email',
            field=models.CharField(default='default@gmail.com', max_length=122),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 26, 17, 35223)),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 12, 26, 17, 35223)),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='winner_email',
            field=models.CharField(default='default@gmail.com', max_length=122),
        ),
    ]
