# Generated by Django 4.1.5 on 2023-04-07 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_user_role_user_is_admin_user_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.date(2023, 4, 7)),
        ),
    ]
