# Generated by Django 4.1.5 on 2023-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_email',
            field=models.EmailField(default='xyz@gmail.com', max_length=254),
        ),
    ]
