# Generated by Django 4.1.5 on 2023-04-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
